TK_D12/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('tinymce', include('tinymce.urls')),
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('schedule/', include('Schedule.urls')),
    path('doctor/', include('doctor.urls', namespace='doctor')),
    path('', include('article.urls', namespace='article')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'article'

urlpatterns = [
    path('article/', views.article, name='article'),
    path('news/<slug:slug>/', views.news, name='news'),
    path('tipsandtrick/<slug:slug>/', views.tipsandtrick, name='tipsandtrick'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.Register, name='register'),
    path('', include('django.contrib.auth.urls'), name='django-auth'),
]

article/models.py
from django.db import models
from django.contrib.auth.models import User
from tinymce import models as tinymce_models, HTMLField


# Create your models here.
class News(models.Model):
    title = models.CharField(max_length=100, default="")
    slug = models.SlugField(unique=True, max_length=100, default="")
    date = models.DateField(auto_now_add=True)
    content = HTMLField('Content')
    image = models.ImageField(null=True, blank=True, upload_to='image')

    def __str__(self):
        return self.title

class TipsAndTrick(models.Model):
    title = models.CharField(max_length=100, default="")
    slug = models.SlugField(unique=True, max_length=100, default="")
    date = models.DateField(auto_now_add=True)
    content = HTMLField('Content')
    image = models.ImageField(null=True, blank=True, upload_to='image')

    def __str__(self):
        return self.title

class CommentsNews(models.Model):
    post = models.ForeignKey(News,on_delete=models.CASCADE,related_name='comments_news')
    user = models.ForeignKey(User, on_delete= models.CASCADE,related_name='comments_news_posts', default="")
    comment = models.TextField()
    published = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['published']

    def __str__(self):
        return 'Comment {} by {}'.format(self.comment, self.user)

class CommentsTipsAndTrick(models.Model):
    post = models.ForeignKey(TipsAndTrick,on_delete=models.CASCADE,related_name='comments_tips_and_trick')
    user = models.ForeignKey(User, on_delete= models.CASCADE,related_name='comments_tips_and_trick_posts', default="")
    comment = models.TextField()
    published = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['published']

    def __str__(self):
        return 'Comment {} by {}'.format(self.comment, self.user)

article/forms.py
from .models import *
from django import forms

class CommentNewsForm(forms.ModelForm):
    class Meta:
        model = CommentsNews
        fields = ('comment',)


class CommentTipsAndTrickForm(forms.ModelForm):
    class Meta:
        model = CommentsTipsAndTrick
        fields = ('comment',)

article/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from .forms import *

# Create your views here.
def article(request):
    news = News.objects.all()
    tips = TipsAndTrick.objects.all()
    context = {
        "news": news,
        "tips": tips
    }
    return render(request, "article.html", context)

def news(request, slug):
    post = get_object_or_404(News, slug=slug)
    
    if request.method == 'POST':
        comment_form = CommentNewsForm(data=request.POST)
        if comment_form.is_valid():
            comment_form.save()
            comment_form = CommentNewsForm()
    else:
        comment_form = CommentNewsForm()

    comments = post.comments_news.filter(active=True)

    context = {
        'post': post,
        'comment_form': comment_form,
        'comments': comments,        
    }
    return render(request, 'news.html', context)

def tipsandtrick(request, slug):
    post = get_object_or_404(TipsAndTrick, slug=slug)

    if request.method == 'POST':
        comment_form = CommentTipsAndTrickForm(data=request.POST)
        if comment_form.is_valid():
            comment_form.save()
            comment_form = CommentTipsAndTrickForm()
    else:
        comment_form = CommentTipsAndTrickForm()

    comments = post.comments_tips_and_trick.filter(active=True)

    context = {
        'post' : post,
        'comment_form': comment_form,
        'comments': comments,
    }
    return render(request, 'tipsandtrick.html', context)

article/templates/article.html
{% extends 'home/base.html' %}
{% load static %}
<head>
    {% block css %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/css/flag-icon.min.css" rel="stylesheet">

    <!-- Font Google -->
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap" rel="stylesheet">

    <!-- Bootstrap Javascript -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <title>Article</title>

    <style>
        .news-image, .tips-image {
            width: 70%;
        }
        
        .news-title, .tips-title {
            padding-top: 1rem;
        }
        
        #news, #tipsandtrick {
            padding: 7% 15%;
        }
        
        #tipsandtrick {
            
        }

        .news-box, .tips-box{
            text-align: center;
            font-family: "Lato", sans-serif;
            font-weight: bold;
            padding: 5%;
        }
    </style>
    {% endblock css %}
    
</head>

<body>

    

{% block content %}  
<section id="news">
    <h2>NEWS</h2>

    <div class="row">
        {% for item in news %}
        <div class="news-box col-lg-6">
          {% if item.image %}  
            <img class="news-image" src="{{item.image.url}}" alt="{{item.title}}">
          {% endif %}
          <a href="{% url 'article:news' slug=item.slug %}"><h6 class="news-title">{{item.title}}</h6></a>
        </div>
        {% endfor %}
    </div>

</section>

<section id="tipsandtrick">
    <h2>TIPS AND TRICK</h2>

    <div class="row">
        {% for item in tips %}
        <div class="tips-box col-lg-6">
          {% if item.image %}  
            <img class="tips-image" src="{{item.image.url}}" alt="{{item.title}}">
          {% endif %}
          <a href="{% url 'article:tipsandtrick' slug=item.slug %}"><h6 class="tips-title">{{item.title}}</h6></a>
        </div>
        {% endfor %}
    </div>
{% endblock content %}
</section>


</body>
</html>

article/templates/news.html
{% extends 'home/base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    {% block css %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/css/flag-icon.min.css" rel="stylesheet">

    <!-- Bootstrap Javascript -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>

    <title>{{post.title}}</title>

    <style>
        @import url('https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap');

        #detail {
            padding: 7% 15%;

        }

        .detail-title {
            text-align: center;
            color: #154440;
        }

        .detail-image {
            width: 50%;
            display: block;
            margin-top: auto;
            margin-left: auto;
            margin-right: auto;
            text-align: center;
        }

        .content,
        .detail-title {
            font-family: "Lato", sans-serif;
        }

        .detail-title,
        .detail-date {
            font-weight: bold;
        }

        .content {
            font-size: larger;
            text-align: justify;
            color: black;
        }
    </style>
    {% endblock css %}



</head>

<body>
    {% block content %}
    <section id="detail">
        {% if post.image %}
        <img src='{{post.image.url}}' class="detail-image" alt="{{post.title}}">
        {% endif %}
        <br>
        <h1 class="detail-title">{{post.title}}</h1>
        <br>
        <h6 class="detail-date">{{post.date}}</h6>
        <br>
        <div class="content">
            {% autoescape off %}
            {{post.content | safe}}
            {% endautoescape %}
        </div>


        <h3>Leave a Comment</h3>

        {% load crispy_forms_tags %}

        <form method="post" action="">
            <fieldset>
                {{ comment_form | crispy}}
                {% csrf_token %}
                <br>
                <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
            </fieldset>
        </form>

        <br>
        <h3>{{comments.count}} Comments</h3>

        {% for comment in comments %}
        <div class="comments" style="padding: 10px;">
            <p class="font-weight-bold">
                {{ comment.user }}
                <span class=" text-muted font-weight-normal">
                    {{ comment.published }}
                </span>
            </p>
            {{ comment.comment | linebreaks }}
        </div>
        {% endfor %}


    </section>

    {% endblock content %}
</body>

</html>

article/templates/tipsandtrick.html
{% extends 'home/base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    {% block css %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/css/flag-icon.min.css" rel="stylesheet">

    <!-- Bootstrap Javascript -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>

    <title>{{post.title}}</title>

    <style>
        @import url('https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap');

        #detail {
            padding: 7% 15%;

        }

        .detail-title {
            text-align: center;
            color: #154440;
        }

        .detail-image {
            width: 50%;
            display: block;
            margin-top: auto;
            margin-left: auto;
            margin-right: auto;
            text-align: center;
        }

        .content,
        .detail-title {
            font-family: "Lato", sans-serif;
        }

        .detail-title,
        .detail-date {
            font-weight: bold;
        }

        .content {
            font-size: larger;
            text-align: justify;
            color: black;
        }
    </style>

    {% endblock css %}



</head>

<body>



    {% block content %}
    <div id="detail">
        {% if post.image %}
        <img src='{{post.image.url}}' class="detail-image" alt="{{post.title}}">
        {% endif %}
        <br> <br>
        <h1 class="detail-title">{{post.title}}</h1>
        <br>
        <h6 class="detail-date">{{post.date}}</h6>
        <br>
        <div class="content">
            {% autoescape off %}
            {{post.content | safe}}
            {% endautoescape %}
        </div>

        <h3>Leave a Comment</h3>

        {% load crispy_forms_tags %}

        <form method="post" action="">
            <fieldset>

                {{ comment_form | crispy}}
                {% csrf_token %}
                <br>
                <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
            </fieldset>
        </form>

        <br>
        <h3>{{comments.count}} Comments</h3>
        
        {% for comment in comments %}
        <div class="comments" style="padding: 10px;">
          <p class="font-weight-bold">
            {{ comment.user }}
            <span class=" text-muted font-weight-normal">
              {{ comment.published }}
            </span>
          </p>
          {{ comment.comment | linebreaks }}
        </div>
        {% endfor %}

    </div>
    {% endblock content %}
</body>

</html>